name: Run RSpec with ActiveSupport 7.0

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: .github/gemfiles/rails7_0.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        memcached-version: ['1.6.26']
    steps:
      - uses: actions/checkout@v4

      - name: Install Memcached ${{ matrix.memcached-version }}
        working-directory: .github/scripts
        env:
          MEMCACHED_VERSION: ${{ matrix.memcached-version }}
        run: |
          chmod +x ./install_memcached.sh
          ./install_memcached.sh

      - name: Setup Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake spec
